---
- Calendar:
    - Media Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 10
          showTime: true
          timezone: America/Los_Angeles
          integrations:
            - type: ical # Show calendar events from another service
              url: https://calendar.google.com/calendar/ical/7lc79or2gm6vc4ne18tbupipb4%40group.calendar.google.com/public/basic.ics # URL with calendar events
              name: Family Calendar # required - name for these calendar events
              color: zinc # optional - defaults to pre-defined color for the service (zinc for ical)
              params: # optional - additional params for the service
                showName: true # optional - show name before event title in event line - defaults to false
- Network and IoT:
    - NextDNS:
        icon: nextdns.svg
        href: "https://my.nextdns.io/"
        description: DNS and Spam Filter
        widget:
          type: nextdns
          profile: 734738
          key: cf7f5ca75ab3d2fcd6b87ee4368de666fc44cff6
    - Unifi:
        icon: ubiquiti.svg
        href: "https://192.168.10.1/"
        description: Nextwork Controller
        widget:
            type: unifi
            url: https://192.168.10.1/
            username: robert@robertfarrington.com
            password: Cag@8awe
    - Home Assistant:
        icon: home-assistant.svg
        href: "http://homeassistant.local:8123/"
        description: Home Automation
        widget:
          type: homeassistant
          url: 192.168.10.167:8123
          key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhMGMyN2YyZjU2Y2E0OTNkOGE0ZTFhZjAxYTg0ODI4NCIsImlhdCI6MTczNjY1NTgwMCwiZXhwIjoyMDUyMDE1ODAwfQ.lRSHZbDpNVpGfxeSYTpqHWZYS72OIgzeHkGLc_m9CMo"
          custom:
            - state: speedtest_download
            - state: sensor.butterfly_san_diego_sensors_temperature
            - state: sensor.living_room_temperature
    - Uptime Robot:
        icon: uptime-kuma.svg
        href: "https://dashboard.uptimerobot.com"
        description: Status Monitor
        widget:
          type: uptimerobot
          url: https://api.uptimerobot.com
          key: ur1394528-6ac2a91c0af14912b463aab7
    - Protect:
        icon: unifi-protect
        href: https://192.168.10.109/
        description: Security
    - Cloudflare:
        icon: cloudflare.svg
        href: https://dash.cloudflare.com
        description: Public DNS
    - Portainer:
        icon: portainer.svg
        href: "http://192.168.10.127:9000"
        description: Portainer GUI
- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Media Player
        widget:
          type: jellyfin
          url: http://192.168.0.115:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_TOKEN}}"
          enableBlocks: true
          enableNowPlaying: true
    - Jellyseerr:
        icon: jellyseerr.svg
        href: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
        description: Media Requests
        widget:
          type: jellyseerr
          url: http://192.168.0.115:5055
          key: "{{HOMEPAGE_VAR_JELLYSEERR_API_TOKEN}}"
    - Navidrome:
        icon: navidrome.svg
        href: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
        description: Self-hosted Music
        widget:
          type: navidrome
          url: http://192.168.0.115:4533
          user: ian
          token: "{{HOMEPAGE_VAR_NAVIDROME_API_TOKEN}}"
          salt: "{{HOMEPAGE_VAR_NAVIDROME_API_SALT}}"
          # Navidrome's (Subsonic) API requires a much more in-depth configuration: https://www.subsonic.org/pages/api.jsp
    - Immich:
        icon: immich.svg
        href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        description: Photos
        widget:
          type: immich
          url: http://192.168.0.115:8760
          key: "{{HOMEPAGE_VAR_IMMICH_API_TOKEN}}"
- Tor Stack:
    - qBittorrent:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
        description: Linux ISO Server
        widget:
          type: qbittorrent
          url: http://192.168.0.115:8080
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
    - Radarr:
        icon: radarr.svg
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        description: Movie Pull Automation
        widget:
          type: radarr
          url: http://192.168.0.115:7878
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
          enableQueue: false
    - Sonarr:
        icon: sonarr.svg
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        description: TV Pull Automation
        widget:
          type: sonarr
          url: http://192.168.0.115:8989
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
          enableQueue: false
    - Lidarr:
        icon: lidarr.svg
        href: "{{HOMEPAGE_VAR_LIDARR_URL}}"
        description: Music Pull Automation
        widget:
          type: lidarr
          url: null
    - Readarr:
        icon: readarr.svg
        href: "{{HOMEPAGE_VAR_READARR_URL}}"
        description: eBook Pull Automation
        widget:
          type: readarr
          url: http://192.168.0.115:8787
          key: "{{HOMEPAGE_VAR_READARR_API_KEY}}"
          enableQueue: false
    - Bazarr:
        icon: bazarr.svg
        href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
        description: Subtitle Pull Automation
        widget:
          type: bazarr
          url: http://192.168.0.115:6767
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
    - Prowlarr:
        icon: prowlarr.svg
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        description: Index Pull Automation
        widget:
          type: prowlarr
          url: http://192.168.0.115:9696
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
          enableQueue: false
    - Access and Services:
        - Vaultwarden:
            icon: bitwarden.svg
            href: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
            description: Self-hosted Bitwarden Admin Interface
        - IPMI:
            icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
            href: "{{HOMEPAGE_VAR_IPMI_URL}}"
            description: Unraid IPMI
            siteMonitor: https://192.168.0.40
        - Netboot:
            icon: https://netboot.xyz/img/nbxyz-laptop.gif
            href: "{{HOMEPAGE_VAR_NETBOOT_URL}}"
            description: Network Boot
